const services = [
  {
    id: 1,
    slug: 'app-design',
    title: 'App Design',
    text: 'Praesent placerated egestas egestas cras rhone magna rutrum tellus laoreet',
    icon: '/images/services-1.svg',
    color: '#E3F8FA',
    feature: true,
  },
  {
    id: 2,
    slug: 'web-design',
    title: 'Web Design',
    text: 'Praesent placerated egestas egestas cras rhone magna rutrum tellus laoreet',
    icon: '/images/services-2.svg',
    color: '#F4ECE0',
    feature: true,
  },
  {
    id: 3,
    slug: 'web-development',
    title: 'Web Development',
    text: 'Praesent placerated egestas egestas cras rhone magna rutrum tellus laoreet',
    icon: '/images/services-3.svg',
    color: '#F5E6FE',
    feature: true,
  },
  {
    id: 4,
    slug: 'interfase-design',
    title: 'Interface Design',
    text: 'Praesent placerated egestas egestas cras rhone magna rutrum tellus laoreet',
    icon: '/images/services-4.svg',
    color: '#FFE6E2',
    feature: true,
  },
  {
    id: 5,
    slug: 'visual-design',
    title: 'Visual Design',
    text: 'Praesent placerated egestas egestas cras rhone magna rutrum tellus laoreet',
    icon: '/images/services-5.svg',
    color: '#E0E6F4',
    feature: false,
  },
  {
    id: 6,
    slug: 'uxui-design',
    title: 'Ux Design',
    text: 'Praesent placerated egestas egestas cras rhone magna rutrum tellus laoreet',
    icon: '/images/services-6.svg',
    color: '#E2FAE3',
    feature: false,
  },
];

export default services;